[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer', 'nginx']

[phases.build]
cmds = ['echo "Building PHP application..."']

[phases.start]
cmd = 'php -S 0.0.0.0:$PORT -t .'

[variables]
PHP_VERSION = '8.1'
