name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cars_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, pdo, pdo_mysql
        
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
          sleep 1
        done
        
    - name: Create test database and tables
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot cars_test < db/cars.sql
        
    - name: Run PHP syntax check
      run: find . -name "*.php" -exec php -l {} \;
      
    - name: Run basic connection test
      run: |
        php -r "
        \$host = '127.0.0.1';
        \$user = 'root';
        \$pass = 'root';
        \$db = 'cars_test';
        \$conn = new mysqli(\$host, \$user, \$pass, \$db);
        if(\$conn->connect_error) {
          echo 'Connection failed: ' . \$conn->connect_error;
          exit(1);
        }
        echo 'Database connection successful';
        \$conn->close();
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v1.2.0
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
